import BaseDecimal from 'decimal.js';
import raw from '../../../../config/execution-v1.json';
export const D = BaseDecimal.clone({ precision: 80, rounding: BaseDecimal.ROUND_DOWN });
export const CONFIG = Object.freeze(raw);
export const VERSION = CONFIG.strategyVersion;
export const decimal = (value: string) => {
  if (typeof value !== 'string' || value.length > 512 || !/^-?\d+(?:\.\d+)?$/.test(value)) throw new Error('invalid_decimal');
  const n = new D(value); if (!n.isFinite()) throw new Error('invalid_decimal'); return n;
};
export const positive = (value: string) => { const n = decimal(value); if (!n.gt(0)) throw new Error('nonpositive_value'); return n; };
export const fresh = (at: number, now: number, age: number) => Number.isSafeInteger(at) && at <= now && now - at <= age;
export type Candle = { source: string; symbol: string; openTime: number; closeTime: number;
  open: string; high: string; low: string; close: string; volume: string; complete: boolean };
export type IndicatorState = { count: number; lastCloseTime: number | null; seed: string[];
  ema20: string | null; ema50: string | null; ema200: string | null; slowHistory: string[] };
export type Signal = { id: string; version: string; symbol: string; timeframe: 900; at: number;
  side: 'buy' | 'sell'; close: string; indicators: { ema20: string; ema50: string; ema200: string; ema200FourBack: string } };
export type Quote = { symbol: string; bid: string; ask: string; sourceAt: number; readAt: number; source: string;
  depth?: { bids: { price: string; quantity: string }[]; asks: { price: string; quantity: string }[] } };
export type Costs = { buyFeeRate: string; sellFeeRate: string; buyFixedEur: string; sellFixedEur: string;
  buySlippageRate: string; sellSlippageRate: string; source: string; observedAt: number; depthRequired?: boolean };
export type Instrument = { symbol: string; active: boolean; quoteCurrency: string;
  quantityStep: string; priceStep: string; minimumQuantity: string; minimumNotional: string;
  maximumQuantity: string | null; costs: Costs | null };
export type Position = { id: string; symbol: string; managed: boolean; openedAt: number | null; quantity: string; available: string;
  reserved: string; averageFillPrice: string | null; originalStop: string | null;
  stop: string | null; target: string | null; marketValueEur: string | null;
  valuationAt: number | null; unrealizedNetPnlEur: string | null;
  protectionState: 'active' | 'missing' | 'unknown'; protectionIds: string[];
  exitReason?: 'stop' | 'target' | 'reverse_cross'; exitRevision?: string };
export type SourceOrder = { id: string; clientKey: string; symbol: string; side: 'buy' | 'sell';
  status: 'open' | 'partial' | 'filled' | 'cancelled' | 'rejected' | 'expired' | 'unknown';
  quantity: string | null; filledQuantity: string; remainingBudgetEur: string | null;
  submittedAt: number; sourceAt: number; managed: boolean; purpose: 'entry' | 'exit' | 'protection';
  averageFillPrice: string | null; feeEur: string | null; baseFeeQuantity?: string };
export type ClosedTrade = { id: string; symbol: string; version: string; sourceConfirmed: boolean;
  closedAt: number; netPnlEur: string | null; feesEur: string | null; slippageEur: string | null;
  quantity: string; averageEntryPrice: string | null; originalStop: string | null; sourceOrderIds: string[] };
export type SourceFill = { id: string; orderId: string; symbol: string; side: 'buy' | 'sell';
  at: number; quantity: string; price: string; feeEur: string | null; slippageEur: string | null };
export type EquityObservation = { id: string; at: number; equityEur: string | null;
  netFlowEur: string | null; beforeFlowEquityEur: string | null; transfersComplete: boolean;
  unrealizedNetPnlEur?: string | null;
  // Exact event time, with separately identified historical accounting marks.
  evidence?: { kind: 'source_snapshot' | 'source_ledger'; markAt: number; transactionIds: string[] } };
export type Account = { id: string; sourceAt: number; readAt: number; availableEur: string;
  balances: { currency: string; total: string; available: string; reserved: string }[];
  equityEur: string | null; valuationAt: number | null; valuationComplete: boolean;
  positions: Position[]; orders: SourceOrder[]; trades: ClosedTrade[]; equityHistory: EquityObservation[];
  fills: SourceFill[] | null; reportEvidence?: import('./report-evidence').ReportEvidence;
  tradeHistoryComplete: boolean; archiveStart: number | null; dataBlockers?: string[] };
export type RiskState = { reduced: boolean; dailyHaltDate: string | null };
export type RiskResult = { state: RiskState; allocation: string; reason: string;
  entryBlocked: string | null; drawdown: string | null; dayReturn: string | null;
  consecutiveWins: number | null; consecutiveLosses: number | null; returnIndex: string | null };
export type BuyIntent = { side: 'buy'; symbol: string; signal: Signal; key: string; type: 'limit';
  quantity: string; limitPrice: string; budgetEur: string; allocation: string; allocationReason: string;
  estimatedCostEur: string; estimatedCostFraction: string; expectedEntryFeeEur: string;
  expiresAt: number; stopFraction: string; targetFraction: string; quote: Quote };
export type SellIntent = { side: 'sell'; symbol: string; positionId: string; key: string;
  quantity: string; reason: 'stop' | 'target' | 'reverse_cross'; signal: Signal | null;
  reduceOnly: true; protectionIds: string[]; triggerQuote?: Quote };
export type Intent = BuyIntent | SellIntent;
export type Block = { symbol?: string; reason: string };
export const terminal = (order: SourceOrder) => ['filled', 'cancelled', 'rejected', 'expired'].includes(order.status);

