import { CONFIG, VERSION, type Account, type Candle, type EquityObservation, type Instrument, type Position, type Quote, type Signal, type SourceOrder, type ClosedTrade } from '../src/lib/execution/v1/model';
import { signalId } from '../src/lib/execution/v1/strategy';
import { berlinBounds } from '../src/lib/execution/v1/risk';
// Isolated test inputs, never production balances or generated execution records.
export const NOW = Date.parse('2026-09-26T12:00:00Z') / 1000;
export const candle = (i: number, close = '100'): Candle => ({ source: CONFIG.candleSource, symbol: 'AAA-EUR', openTime: i * 900, closeTime: (i + 1) * 900, open: close, close, high: close, low: close, volume: '1', complete: true });
export const signal = (symbol = 'AAA-EUR', side: 'buy' | 'sell' = 'buy', at = NOW): Signal => ({ id: signalId(symbol, at, side), version: VERSION, symbol, side, at, timeframe: 900, close: '100', indicators: { ema20: '100', ema50: '99', ema200: '90', ema200FourBack: '89' } });
export const quote = (symbol = 'AAA-EUR'): Quote => ({ symbol, bid: '99.99', ask: '100', sourceAt: NOW, readAt: NOW, source: 'test-source' });
export const instrument = (symbol = 'AAA-EUR'): Instrument => ({ symbol, active: true, quoteCurrency: 'EUR', quantityStep: '0.001', priceStep: '0.01', minimumQuantity: '0.001', minimumNotional: '1', maximumQuantity: null, costs: { buyFeeRate: '0.001', sellFeeRate: '0.001', buyFixedEur: '0', sellFixedEur: '0', buySlippageRate: '0.0001', sellSlippageRate: '0.0001', source: 'test-fee-schedule', observedAt: NOW } });
export const valuation = (id: string, at: number, equityEur = '1000', netFlowEur = '0', beforeFlowEquityEur: string | null = null): EquityObservation => ({ id, at, equityEur, netFlowEur, beforeFlowEquityEur, transfersComplete: true });
export const account = (): Account => ({ id: CONFIG.accountId, sourceAt: NOW, readAt: NOW, availableEur: '1000', balances: [{ currency: 'EUR', total: '1000', available: '1000', reserved: '0' }], equityEur: '1000', valuationAt: NOW, valuationComplete: true, positions: [], orders: [], fills: [], trades: [], equityHistory: [valuation('start', berlinBounds(NOW).start), valuation('now', NOW)], tradeHistoryComplete: true, archiveStart: berlinBounds(NOW).start });
export const position = (symbol = 'AAA-EUR'): Position => ({ id: `p:${symbol}`, symbol, managed: true, openedAt: NOW - 3600, quantity: '1', available: '1', reserved: '0', averageFillPrice: '100', stop: '98', originalStop: '98', target: '104', marketValueEur: '100', valuationAt: NOW, unrealizedNetPnlEur: '0', protectionState: 'active', protectionIds: ['oco:1'] });
export const order = (symbol = 'AAA-EUR'): SourceOrder => ({ id: 'source-order', clientKey: 'key', symbol, side: 'buy', status: 'open', quantity: '1', filledQuantity: '0', remainingBudgetEur: '100', submittedAt: NOW, sourceAt: NOW, managed: true, purpose: 'entry', averageFillPrice: null, feeEur: null });
export const trade = (id: string, pnl: string | null, at = NOW - 1): ClosedTrade => ({ id, symbol: 'AAA-EUR', version: VERSION, sourceConfirmed: true, closedAt: at, netPnlEur: pnl, feesEur: '0.2', slippageEur: '0.01', quantity: '1', averageEntryPrice: '100', originalStop: '98', sourceOrderIds: [`buy:${id}`, `sell:${id}`] });
