/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=automation/wrangler.jsonc --include-runtime=false automation/env.d.ts` (hash: 7397463d0e3d7cb4bd667b84863297de)
interface __BaseEnv_Env {
	DB: D1Database;
	EDUCATION_SCHEDULER_SIGNING_KEY_V1: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./education-scheduler");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EDUCATION_SCHEDULER_SIGNING_KEY_V1">> {}
}
