/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=automation/wrangler.jsonc --include-runtime=false automation/env.d.ts` (hash: 641a25273d3571d763ef23b82eb0e3bb)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
